ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'CUSTOMER_PORTAL';
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'CLIENT_PORTAL';
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'COMMUNICATION';
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'PROMOTIONS';
